
BASEPATH:=../../../

REGRESS := 1

PG_CONFIG ?= pg_config

# export pg_config for child make commands (check etc)
export PG_CONFIG

PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)

pg_major_version := $(shell $(PG_CONFIG) --version | awk -F' ' '{ print $$2 }' | awk -F'.' '{ print $$1 }' | awk -F'r' '{ print $$1 }')

EXTENSIONLOAD :=  --load-extension=tsm_system_rows --load-extension=pg_cron --load-extension=vector --load-extension=postgis --load-extension=documentdb_core --load-extension=documentdb

MAKEFILE_DIR := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))
export PATH := $(MAKEFILE_DIR)bin:$(PATH)
export PG_REGRESS_DIFF_OPTS = -dU10

export PGISOLATIONTIMEOUT = 60

.PHONY: check-basic check-minimal

define common_test
	mkdir -p log && { $(top_builddir)/src/test/regress/pg_regress --encoding=UTF8 --dlpath=$(BASEPATH) $(EXTENSIONLOAD) --temp-instance ./tmp --temp-config ./postgresql.conf --host localhost --port 58050 $(1) $(2) 2>&1; echo $$? > log/.exitcode; } | tee log/summary_$(3).out; test $$(cat log/.exitcode) -eq 0 || (cat regression.diffs && false)
endef

define isolation_test
	mkdir -p log && { $(top_builddir)/src/test/isolation/pg_isolation_regress --encoding=UTF8 --dlpath=$(BASEPATH) $(EXTENSIONLOAD) --temp-instance ./tmp --temp-config ./isolation_postgresql.conf --host localhost --port 58051 $(1) $(2) 2>&1; echo $$? > log/.exitcode; } | tee log/summary_$(3).out; test $$(cat log/.exitcode) -eq 0 || (cat regression.diffs && false)
endef

check-basic: generate_version_schedule
	$(call common_test,--schedule=./log/basic_schedule_$(pg_major_version),,documentdb_tests)

check-minimal:
	$(call common_test,--schedule=./minimal_schedule, $(EXTRA_TESTS),documentdb_tests_minimal)

check-test-output:
	./validate_test_output.sh $(pg_major_version) $(MAKEFILE_DIR)

generate_version_schedule:
	@mkdir -p log
	@cp basic_schedule log/basic_schedule_$(pg_major_version)
	@./mutate_schedule.sh log/basic_schedule_$(pg_major_version) $(pg_major_version)

INSTALL_PG_PORT ?= 5432

installcheck: generate_version_schedule
	mkdir -p log && { $(top_builddir)/src/test/regress/pg_regress --encoding=UTF8 --port $(INSTALL_PG_PORT) --dlpath=$(BASEPATH) --use-existing --dbname=postgres --schedule=./log/basic_schedule_$(pg_major_version) 2>&1; echo $$? > log/.exitcode; } | tee log/summary.out; test $$(cat log/.exitcode) -eq 0 || (cat regression.diffs && false)

all: check-basic check-test-output
