/*-------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation.  All rights reserved.
 *
 * documentdb_tests/src/test_setup/config.rs
 *
 *-------------------------------------------------------------------------
 */

use documentdb_gateway_core::configuration::{
    CertInputType, CertificateOptions, DocumentDBSetupConfiguration,
};

pub fn setup_configuration() -> DocumentDBSetupConfiguration {
    let system_user = std::env::var("PostgresSystemUser").unwrap_or(whoami::username());

    DocumentDBSetupConfiguration {
        node_host_name: "localhost".to_string(),
        blocked_role_prefixes: Vec::new(),
        gateway_listen_port: Some(10260),
        allow_transaction_snapshot: Some(false),
        certificate_options: CertificateOptions {
            cert_type: CertInputType::PemAutoGenerated,
            ..Default::default()
        },
        postgres_system_user: system_user.clone(),
        postgres_data_user: system_user,
        ..Default::default()
    }
}

pub fn setup_configuration_with_unix_socket_custom(
    path: Option<String>,
    permissions: Option<String>,
) -> DocumentDBSetupConfiguration {
    let mut config = setup_configuration();
    config.unix_socket_path = path;
    config.unix_socket_file_permissions = permissions;
    config
}
